/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/9.0.89
 * Generated at: 2024-10-28 12:24:54 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp.Views.LandingPage;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;

public final class LandingPage_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent,
                 org.apache.jasper.runtime.JspSourceImports {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  static {
    _jspx_dependants = new java.util.HashMap<java.lang.String,java.lang.Long>(4);
    _jspx_dependants.put("/Views/common/footer.jsp", Long.valueOf(1727878710119L));
    _jspx_dependants.put("jar:file:/C:/Users/This%20PC/.m2/repository/jstl/jstl/1.2/jstl-1.2.jar!/META-INF/c.tld", Long.valueOf(1153359882000L));
    _jspx_dependants.put("/Views/common/header.jsp", Long.valueOf(1729046493002L));
    _jspx_dependants.put("/WEB-INF/lib/jstl-1.2.jar", Long.valueOf(1727369311309L));
  }

  private static final java.util.Set<java.lang.String> _jspx_imports_packages;

  private static final java.util.Set<java.lang.String> _jspx_imports_classes;

  static {
    _jspx_imports_packages = new java.util.LinkedHashSet<>(3);
    _jspx_imports_packages.add("javax.servlet");
    _jspx_imports_packages.add("javax.servlet.http");
    _jspx_imports_packages.add("javax.servlet.jsp");
    _jspx_imports_classes = null;
  }

  private org.apache.jasper.runtime.TagHandlerPool _005fjspx_005ftagPool_005fc_005fif_0026_005ftest;

  private volatile javax.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public java.util.Set<java.lang.String> getPackageImports() {
    return _jspx_imports_packages;
  }

  public java.util.Set<java.lang.String> getClassImports() {
    return _jspx_imports_classes;
  }

  public javax.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
    _005fjspx_005ftagPool_005fc_005fif_0026_005ftest = org.apache.jasper.runtime.TagHandlerPool.getTagHandlerPool(getServletConfig());
  }

  public void _jspDestroy() {
    _005fjspx_005ftagPool_005fc_005fif_0026_005ftest.release();
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
      throws java.io.IOException, javax.servlet.ServletException {

    if (!javax.servlet.DispatcherType.ERROR.equals(request.getDispatcherType())) {
      final java.lang.String _jspx_method = request.getMethod();
      if ("OPTIONS".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        return;
      }
      if (!"GET".equals(_jspx_method) && !"POST".equals(_jspx_method) && !"HEAD".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        response.sendError(HttpServletResponse.SC_METHOD_NOT_ALLOWED, "JSPs only permit GET, POST or HEAD. Jasper also permits OPTIONS");
        return;
      }
    }

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html;charset=UTF-8");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\r\n");
      out.write("\r\n");
      out.write("<html>\r\n");
      out.write("<head>\r\n");
      out.write("  <meta charset=\"utf-8\">\r\n");
      out.write("  <title>Kider - Preschool Website Template</title>\r\n");
      out.write("  <meta content=\"width=device-width, initial-scale=1.0\" name=\"viewport\">\r\n");
      out.write("  <meta content=\"\" name=\"keywords\">\r\n");
      out.write("  <meta content=\"\" name=\"description\">\r\n");
      out.write("\r\n");
      out.write("  <!-- Favicon -->\r\n");
      out.write("  <link href=\"img/favicon.ico\" rel=\"icon\">\r\n");
      out.write("\r\n");
      out.write("  <!-- Google Web Fonts -->\r\n");
      out.write("  <link rel=\"preconnect\" href=\"https://fonts.googleapis.com\">\r\n");
      out.write("  <link rel=\"preconnect\" href=\"https://fonts.gstatic.com\" crossorigin>\r\n");
      out.write("  <link href=\"https://fonts.googleapis.com/css2?family=Heebo:wght@400;500;600&family=Inter:wght@600&family=Lobster+Two:wght@700&display=swap\" rel=\"stylesheet\">\r\n");
      out.write("\r\n");
      out.write("  <!-- Icon Font Stylesheet -->\r\n");
      out.write("  <link href=\"https://cdnjs.cloudflare.com/ajax/libs/font-awesome/5.10.0/css/all.min.css\" rel=\"stylesheet\">\r\n");
      out.write("  <link href=\"https://cdn.jsdelivr.net/npm/bootstrap-icons@1.4.1/font/bootstrap-icons.css\" rel=\"stylesheet\">\r\n");
      out.write("\r\n");
      out.write("  <!-- Libraries Stylesheet -->\r\n");
      out.write("  <link href=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${pageContext.request.contextPath}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/lib/animate/animate.min.css\" rel=\"stylesheet\">\r\n");
      out.write("  <link href=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${pageContext.request.contextPath}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/lib/owlcarousel/assets/owl.carousel.min.css\" rel=\"stylesheet\">\r\n");
      out.write("\r\n");
      out.write("  <!-- Customized Bootstrap Stylesheet -->\r\n");
      out.write("  <link href=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${pageContext.request.contextPath}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/css/bootstrap.min.css\" rel=\"stylesheet\">\r\n");
      out.write("\r\n");
      out.write("  <!-- Template Stylesheet -->\r\n");
      out.write("  <link href=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${pageContext.request.contextPath}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/css/style.css\" rel=\"stylesheet\">\r\n");
      out.write("\r\n");
      out.write("</head>\r\n");
      out.write("<body>\r\n");
      out.write("<div class=\"container-fluid bg-white p-0\">\r\n");
      out.write("  <!-- Spinner Start -->\r\n");
      out.write("  <div id=\"spinner\" class=\"show bg-white position-fixed translate-middle w-100 vh-100 top-50 start-50 d-flex align-items-center justify-content-center\">\r\n");
      out.write("    <div class=\"spinner-border text-primary\" style=\"width: 3rem; height: 3rem;\" role=\"status\">\r\n");
      out.write("      <span class=\"sr-only\">Loading...</span>\r\n");
      out.write("    </div>\r\n");
      out.write("  </div>\r\n");
      out.write("  <!-- Spinner End -->\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("  <!-- Navbar Start -->\r\n");
      out.write("  ");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("<!DOCTYPE html>\r\n");
      out.write("<html>\r\n");
      out.write("<head>\r\n");
      out.write("    <meta charset=\"utf-8\">\r\n");
      out.write("    <title>Kider - Preschool Website Template</title>\r\n");
      out.write("    <meta content=\"width=device-width, initial-scale=1.0\" name=\"viewport\">\r\n");
      out.write("    <meta content=\"\" name=\"keywords\">\r\n");
      out.write("    <meta content=\"\" name=\"description\">\r\n");
      out.write("\r\n");
      out.write("    <!-- Favicon -->\r\n");
      out.write("    <link href=\"img/favicon.ico\" rel=\"icon\">\r\n");
      out.write("\r\n");
      out.write("    <!-- Google Web Fonts -->\r\n");
      out.write("    <link rel=\"preconnect\" href=\"https://fonts.googleapis.com\">\r\n");
      out.write("    <link rel=\"preconnect\" href=\"https://fonts.gstatic.com\" crossorigin>\r\n");
      out.write("    <link href=\"https://fonts.googleapis.com/css2?family=Heebo:wght@400;500;600&family=Inter:wght@600&family=Lobster+Two:wght@700&display=swap\" rel=\"stylesheet\">\r\n");
      out.write("\r\n");
      out.write("    <!-- Icon Font Stylesheet -->\r\n");
      out.write("    <link href=\"https://cdnjs.cloudflare.com/ajax/libs/font-awesome/5.10.0/css/all.min.css\" rel=\"stylesheet\">\r\n");
      out.write("    <link href=\"https://cdn.jsdelivr.net/npm/bootstrap-icons@1.4.1/font/bootstrap-icons.css\" rel=\"stylesheet\">\r\n");
      out.write("\r\n");
      out.write("    <!-- Libraries Stylesheet -->\r\n");
      out.write("    <link href=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${pageContext.request.contextPath}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/lib/animate/animate.min.css\" rel=\"stylesheet\">\r\n");
      out.write("    <link href=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${pageContext.request.contextPath}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/lib/owlcarousel/assets/owl.carousel.min.css\" rel=\"stylesheet\">\r\n");
      out.write("\r\n");
      out.write("    <!-- Customized Bootstrap Stylesheet -->\r\n");
      out.write("    <link href=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${pageContext.request.contextPath}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/css/bootstrap.min.css\" rel=\"stylesheet\">\r\n");
      out.write("\r\n");
      out.write("    <!-- Template Stylesheet -->\r\n");
      out.write("    <link href=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${pageContext.request.contextPath}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/css/style.css\" rel=\"stylesheet\">\r\n");
      out.write("</head>\r\n");
      out.write("<body>\r\n");
      out.write("<nav class=\"navbar navbar-expand-lg bg-white navbar-light sticky-top px-4 px-lg-5 py-lg-0\">\r\n");
      out.write("    <a href=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${pageContext.request.contextPath}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/Views/LandingPage/LandingPage.jsp\" class=\"navbar-brand\">\r\n");
      out.write("        <h1 class=\"m-0 text-primary\"><i class=\"fa fa-book-reader me-3\"></i>KMS</h1>\r\n");
      out.write("    </a>\r\n");
      out.write("    <button type=\"button\" class=\"navbar-toggler\" data-bs-toggle=\"collapse\" data-bs-target=\"#navbarCollapse\">\r\n");
      out.write("        <span class=\"navbar-toggler-icon\"></span>\r\n");
      out.write("    </button>\r\n");
      out.write("    <div class=\"collapse navbar-collapse\" id=\"navbarCollapse\" style=\"margin-left: 200px; font-size: 20px\">\r\n");
      out.write("        <div class=\"navbar-nav mx-auto\">\r\n");
      out.write("            <a href=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${pageContext.request.contextPath}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/Views/HomePage/HomePage.jsp\" class=\"nav-item nav-link active\">Home</a>\r\n");
      out.write("            <a href=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${pageContext.request.contextPath}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/Views/Admin/accountManage\" class=\"nav-item nav-link\">Admin Manage</a>\r\n");
      out.write("            <a href=\"/\" class=\"nav-item nav-link\">About Us</a>\r\n");
      out.write("            <a href=\"\" class=\"nav-item nav-link\">Contact Us</a>\r\n");
      out.write("        </div>\r\n");
      out.write("        <ul class=\"navbar-nav ml-auto\" style=\"font-size: 20px\">\r\n");
      out.write("            ");
      if (_jspx_meth_c_005fif_005f0(_jspx_page_context))
        return;
      out.write("\r\n");
      out.write("        </ul>\r\n");
      out.write("    </div>\r\n");
      out.write("    <div class=\"collapse navbar-collapse\" style=\"margin-left: 150px; font-size: 20px\">\r\n");
      out.write("        <ul class=\"navbar-nav ml-auto\">\r\n");
      out.write("            ");
      if (_jspx_meth_c_005fif_005f1(_jspx_page_context))
        return;
      out.write("\r\n");
      out.write("        </ul>\r\n");
      out.write("    </div>\r\n");
      out.write("</nav>\r\n");
      out.write("</body>\r\n");
      out.write("</html>\r\n");
      out.write("\r\n");
      out.write("  <!-- Navbar End -->\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("  <!-- Carousel Start -->\r\n");
      out.write("  <div class=\"container-fluid p-0 mb-5\">\r\n");
      out.write("    <div class=\"owl-carousel header-carousel position-relative\">\r\n");
      out.write("      <div class=\"owl-carousel-item position-relative\">\r\n");
      out.write("        <img class=\"img-fluid\" src=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${pageContext.request.contextPath}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/img/carousel-1.jpg\" alt=\"\">\r\n");
      out.write("        <div class=\"position-absolute top-0 start-0 w-100 h-100 d-flex align-items-center\" style=\"background: rgba(0, 0, 0, .2);\">\r\n");
      out.write("          <div class=\"container\">\r\n");
      out.write("            <div class=\"row justify-content-start\">\r\n");
      out.write("              <div class=\"col-10 col-lg-8\">\r\n");
      out.write("                <h1 class=\"display-2 text-white mb-4\">The Best Kindergarten School For Your Child</h1>\r\n");
      out.write("                <p class=\"fs-5 fw-medium text-white mb-4 pb-2\">Vero elitr justo clita lorem. Ipsum dolor at sed stet sit diam no. Kasd rebum ipsum et diam justo clita et kasd rebum sea elitr.</p>\r\n");
      out.write("                <a href=\"\" class=\"btn btn-primary rounded-pill py-sm-3 px-sm-5 me-3\">Learn More</a>\r\n");
      out.write("                <a href=\"\" class=\"btn btn-dark rounded-pill py-sm-3 px-sm-5\">Our Classes</a>\r\n");
      out.write("              </div>\r\n");
      out.write("            </div>\r\n");
      out.write("          </div>\r\n");
      out.write("        </div>\r\n");
      out.write("      </div>\r\n");
      out.write("    </div>\r\n");
      out.write("  </div>\r\n");
      out.write("  <!-- Carousel End -->\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("  <!-- Facilities Start -->\r\n");
      out.write("  <div class=\"container-xxl py-5\">\r\n");
      out.write("    <div class=\"container\">\r\n");
      out.write("      <div class=\"text-center mx-auto mb-5\" style=\"max-width: 600px;\">\r\n");
      out.write("        <h1 class=\"mb-3\">School Facilities</h1>\r\n");
      out.write("        <p>Eirmod sed ipsum dolor sit rebum labore magna erat. Tempor ut dolore lorem kasd vero ipsum sit eirmod sit. Ipsum diam justo sed rebum vero dolor duo.</p>\r\n");
      out.write("      </div>\r\n");
      out.write("      <div class=\"row g-4\">\r\n");
      out.write("        <div class=\"col-lg-3 col-sm-6\">\r\n");
      out.write("          <div class=\"facility-item\">\r\n");
      out.write("            <div class=\"facility-icon bg-primary\">\r\n");
      out.write("              <span class=\"bg-primary\"></span>\r\n");
      out.write("              <i class=\"fa fa-bus-alt fa-3x text-primary\"></i>\r\n");
      out.write("              <span class=\"bg-primary\"></span>\r\n");
      out.write("            </div>\r\n");
      out.write("            <div class=\"facility-text bg-primary\">\r\n");
      out.write("              <h3 class=\"text-primary mb-3\">School Bus</h3>\r\n");
      out.write("              <p class=\"mb-0\">Eirmod sed ipsum dolor sit rebum magna erat lorem kasd vero ipsum sit</p>\r\n");
      out.write("            </div>\r\n");
      out.write("          </div>\r\n");
      out.write("        </div>\r\n");
      out.write("        <div class=\"col-lg-3 col-sm-6\">\r\n");
      out.write("          <div class=\"facility-item\">\r\n");
      out.write("            <div class=\"facility-icon bg-success\">\r\n");
      out.write("              <span class=\"bg-success\"></span>\r\n");
      out.write("              <i class=\"fa fa-futbol fa-3x text-success\"></i>\r\n");
      out.write("              <span class=\"bg-success\"></span>\r\n");
      out.write("            </div>\r\n");
      out.write("            <div class=\"facility-text bg-success\">\r\n");
      out.write("              <h3 class=\"text-success mb-3\">Playground</h3>\r\n");
      out.write("              <p class=\"mb-0\">Eirmod sed ipsum dolor sit rebum magna erat lorem kasd vero ipsum sit</p>\r\n");
      out.write("            </div>\r\n");
      out.write("          </div>\r\n");
      out.write("        </div>\r\n");
      out.write("        <div class=\"col-lg-3 col-sm-6\">\r\n");
      out.write("          <div class=\"facility-item\">\r\n");
      out.write("            <div class=\"facility-icon bg-warning\">\r\n");
      out.write("              <span class=\"bg-warning\"></span>\r\n");
      out.write("              <i class=\"fa fa-home fa-3x text-warning\"></i>\r\n");
      out.write("              <span class=\"bg-warning\"></span>\r\n");
      out.write("            </div>\r\n");
      out.write("            <div class=\"facility-text bg-warning\">\r\n");
      out.write("              <h3 class=\"text-warning mb-3\">Healthy Canteen</h3>\r\n");
      out.write("              <p class=\"mb-0\">Eirmod sed ipsum dolor sit rebum magna erat lorem kasd vero ipsum sit</p>\r\n");
      out.write("            </div>\r\n");
      out.write("          </div>\r\n");
      out.write("        </div>\r\n");
      out.write("        <div class=\"col-lg-3 col-sm-6\">\r\n");
      out.write("          <div class=\"facility-item\">\r\n");
      out.write("            <div class=\"facility-icon bg-info\">\r\n");
      out.write("              <span class=\"bg-info\"></span>\r\n");
      out.write("              <i class=\"fa fa-chalkboard-teacher fa-3x text-info\"></i>\r\n");
      out.write("              <span class=\"bg-info\"></span>\r\n");
      out.write("            </div>\r\n");
      out.write("            <div class=\"facility-text bg-info\">\r\n");
      out.write("              <h3 class=\"text-info mb-3\">Positive Learning</h3>\r\n");
      out.write("              <p class=\"mb-0\">Eirmod sed ipsum dolor sit rebum magna erat lorem kasd vero ipsum sit</p>\r\n");
      out.write("            </div>\r\n");
      out.write("          </div>\r\n");
      out.write("        </div>\r\n");
      out.write("      </div>\r\n");
      out.write("    </div>\r\n");
      out.write("  </div>\r\n");
      out.write("  <!-- Facilities End -->\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("  <!-- About Start -->\r\n");
      out.write("  <div class=\"container-xxl py-5\">\r\n");
      out.write("    <div class=\"container\">\r\n");
      out.write("      <div class=\"row g-5 align-items-center\">\r\n");
      out.write("        <div class=\"col-lg-6\">\r\n");
      out.write("          <h1 class=\"mb-4\">Learn More About Our Work And Our Cultural Activities</h1>\r\n");
      out.write("          <p>Tempor erat elitr rebum at clita. Diam dolor diam ipsum sit. Aliqu diam amet diam et eos. Clita erat ipsum et lorem et sit, sed stet lorem sit clita duo justo magna dolore erat amet</p>\r\n");
      out.write("          <p class=\"mb-4\">Stet no et lorem dolor et diam, amet duo ut dolore vero eos. No stet est diam rebum amet diam ipsum. Clita clita labore, dolor duo nonumy clita sit at, sed sit sanctus dolor eos, ipsum labore duo duo sit no sea diam. Et dolor et kasd ea. Eirmod diam at dolor est vero nonumy magna.</p>\r\n");
      out.write("          <div class=\"row g-4 align-items-center\">\r\n");
      out.write("            <div class=\"col-sm-6\">\r\n");
      out.write("              <a class=\"btn btn-primary rounded-pill py-3 px-5\" href=\"\">Read More</a>\r\n");
      out.write("            </div>\r\n");
      out.write("            <div class=\"col-sm-6\">\r\n");
      out.write("              <div class=\"d-flex align-items-center\">\r\n");
      out.write("                <img class=\"rounded-circle flex-shrink-0\" src=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${pageContext.request.contextPath}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/img/user.jpg\" alt=\"\" style=\"width: 45px; height: 45px;\">\r\n");
      out.write("                <div class=\"ms-3\">\r\n");
      out.write("                  <h6 class=\"text-primary mb-1\">Jhon Doe</h6>\r\n");
      out.write("                  <small>CEO & Founder</small>\r\n");
      out.write("                </div>\r\n");
      out.write("              </div>\r\n");
      out.write("            </div>\r\n");
      out.write("          </div>\r\n");
      out.write("        </div>\r\n");
      out.write("        <div class=\"col-lg-6 about-img\">\r\n");
      out.write("          <div class=\"row\">\r\n");
      out.write("            <div class=\"col-12 text-center\">\r\n");
      out.write("              <img class=\"img-fluid w-75 rounded-circle bg-light p-3\" src=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${pageContext.request.contextPath}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/img/about-1.jpg\" alt=\"\">\r\n");
      out.write("            </div>\r\n");
      out.write("            <div class=\"col-6 text-start\" style=\"margin-top: -150px;\">\r\n");
      out.write("              <img class=\"img-fluid w-100 rounded-circle bg-light p-3\" src=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${pageContext.request.contextPath}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/img/about-2.jpg\" alt=\"\">\r\n");
      out.write("            </div>\r\n");
      out.write("            <div class=\"col-6 text-end\" style=\"margin-top: -150px;\">\r\n");
      out.write("              <img class=\"img-fluid w-100 rounded-circle bg-light p-3\" src=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${pageContext.request.contextPath}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/img/about-3.jpg\" alt=\"\">\r\n");
      out.write("            </div>\r\n");
      out.write("          </div>\r\n");
      out.write("        </div>\r\n");
      out.write("      </div>\r\n");
      out.write("    </div>\r\n");
      out.write("  </div>\r\n");
      out.write("  <!-- About End -->\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("  <!-- Team Start -->\r\n");
      out.write("  <div class=\"container-xxl py-5\">\r\n");
      out.write("    <div class=\"container\">\r\n");
      out.write("      <div class=\"text-center mx-auto mb-5\" style=\"max-width: 600px;\">\r\n");
      out.write("        <h1 class=\"mb-3\">Popular Teachers</h1>\r\n");
      out.write("        <p>Eirmod sed ipsum dolor sit rebum labore magna erat. Tempor ut dolore lorem kasd vero ipsum sit\r\n");
      out.write("          eirmod sit. Ipsum diam justo sed rebum vero dolor duo.</p>\r\n");
      out.write("      </div>\r\n");
      out.write("      <div class=\"row g-4\">\r\n");
      out.write("        <div class=\"col-lg-4 col-md-6\">\r\n");
      out.write("          <div class=\"team-item position-relative\">\r\n");
      out.write("            <img class=\"img-fluid rounded-circle w-75\" src=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${pageContext.request.contextPath}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/img/team-1.jpg\" alt=\"\">\r\n");
      out.write("            <div class=\"team-text\">\r\n");
      out.write("              <h3>Full Name</h3>\r\n");
      out.write("              <p>Designation</p>\r\n");
      out.write("              <div class=\"d-flex align-items-center\">\r\n");
      out.write("                <a class=\"btn btn-square btn-primary mx-1\" href=\"\"><i class=\"fab fa-facebook-f\"></i></a>\r\n");
      out.write("                <a class=\"btn btn-square btn-primary  mx-1\" href=\"\"><i class=\"fab fa-twitter\"></i></a>\r\n");
      out.write("                <a class=\"btn btn-square btn-primary  mx-1\" href=\"\"><i class=\"fab fa-instagram\"></i></a>\r\n");
      out.write("              </div>\r\n");
      out.write("            </div>\r\n");
      out.write("          </div>\r\n");
      out.write("        </div>\r\n");
      out.write("        <div class=\"col-lg-4 col-md-6\">\r\n");
      out.write("          <div class=\"team-item position-relative\">\r\n");
      out.write("            <img class=\"img-fluid rounded-circle w-75\" src=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${pageContext.request.contextPath}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/img/team-2.jpg\" alt=\"\">\r\n");
      out.write("            <div class=\"team-text\">\r\n");
      out.write("              <h3>Full Name</h3>\r\n");
      out.write("              <p>Designation</p>\r\n");
      out.write("              <div class=\"d-flex align-items-center\">\r\n");
      out.write("                <a class=\"btn btn-square btn-primary mx-1\" href=\"\"><i class=\"fab fa-facebook-f\"></i></a>\r\n");
      out.write("                <a class=\"btn btn-square btn-primary  mx-1\" href=\"\"><i class=\"fab fa-twitter\"></i></a>\r\n");
      out.write("                <a class=\"btn btn-square btn-primary  mx-1\" href=\"\"><i class=\"fab fa-instagram\"></i></a>\r\n");
      out.write("              </div>\r\n");
      out.write("            </div>\r\n");
      out.write("          </div>\r\n");
      out.write("        </div>\r\n");
      out.write("        <div class=\"col-lg-4 col-md-6\">\r\n");
      out.write("          <div class=\"team-item position-relative\">\r\n");
      out.write("            <img class=\"img-fluid rounded-circle w-75\" src=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${pageContext.request.contextPath}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/img/team-3.jpg\" alt=\"\">\r\n");
      out.write("            <div class=\"team-text\">\r\n");
      out.write("              <h3>Full Name</h3>\r\n");
      out.write("              <p>Designation</p>\r\n");
      out.write("              <div class=\"d-flex align-items-center\">\r\n");
      out.write("                <a class=\"btn btn-square btn-primary mx-1\" href=\"\"><i class=\"fab fa-facebook-f\"></i></a>\r\n");
      out.write("                <a class=\"btn btn-square btn-primary  mx-1\" href=\"\"><i class=\"fab fa-twitter\"></i></a>\r\n");
      out.write("                <a class=\"btn btn-square btn-primary  mx-1\" href=\"\"><i class=\"fab fa-instagram\"></i></a>\r\n");
      out.write("              </div>\r\n");
      out.write("            </div>\r\n");
      out.write("          </div>\r\n");
      out.write("        </div>\r\n");
      out.write("      </div>\r\n");
      out.write("    </div>\r\n");
      out.write("  </div>\r\n");
      out.write("  <!-- Team End -->\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("  <!-- Testimonial Start -->\r\n");
      out.write("  <div class=\"container-xxl py-5\">\r\n");
      out.write("    <div class=\"container\">\r\n");
      out.write("      <div class=\"text-center mx-auto mb-5\" style=\"max-width: 600px;\">\r\n");
      out.write("        <h1 class=\"mb-3\">Our Clients Say!</h1>\r\n");
      out.write("        <p>Eirmod sed ipsum dolor sit rebum labore magna erat. Tempor ut dolore lorem kasd vero ipsum sit eirmod sit. Ipsum diam justo sed rebum vero dolor duo.</p>\r\n");
      out.write("      </div>\r\n");
      out.write("      <div class=\"owl-carousel testimonial-carousel\">\r\n");
      out.write("        <div class=\"testimonial-item bg-light rounded p-5\">\r\n");
      out.write("          <p class=\"fs-5\">Tempor stet labore dolor clita stet diam amet ipsum dolor duo ipsum rebum stet dolor amet diam stet. Est stet ea lorem amet est kasd kasd erat eos</p>\r\n");
      out.write("          <div class=\"d-flex align-items-center bg-white me-n5\" style=\"border-radius: 50px 0 0 50px;\">\r\n");
      out.write("            <img class=\"img-fluid flex-shrink-0 rounded-circle\" src=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${pageContext.request.contextPath}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/img/testimonial-1.jpg\" style=\"width: 90px; height: 90px;\">\r\n");
      out.write("            <div class=\"ps-3\">\r\n");
      out.write("              <h3 class=\"mb-1\">Client Name</h3>\r\n");
      out.write("              <span>Profession</span>\r\n");
      out.write("            </div>\r\n");
      out.write("            <i class=\"fa fa-quote-right fa-3x text-primary ms-auto d-none d-sm-flex\"></i>\r\n");
      out.write("          </div>\r\n");
      out.write("        </div>\r\n");
      out.write("        <div class=\"testimonial-item bg-light rounded p-5\">\r\n");
      out.write("          <p class=\"fs-5\">Tempor stet labore dolor clita stet diam amet ipsum dolor duo ipsum rebum stet dolor amet diam stet. Est stet ea lorem amet est kasd kasd erat eos</p>\r\n");
      out.write("          <div class=\"d-flex align-items-center bg-white me-n5\" style=\"border-radius: 50px 0 0 50px;\">\r\n");
      out.write("            <img class=\"img-fluid flex-shrink-0 rounded-circle\" src=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${pageContext.request.contextPath}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/img/testimonial-2.jpg\" style=\"width: 90px; height: 90px;\">\r\n");
      out.write("            <div class=\"ps-3\">\r\n");
      out.write("              <h3 class=\"mb-1\">Client Name</h3>\r\n");
      out.write("              <span>Profession</span>\r\n");
      out.write("            </div>\r\n");
      out.write("            <i class=\"fa fa-quote-right fa-3x text-primary ms-auto d-none d-sm-flex\"></i>\r\n");
      out.write("          </div>\r\n");
      out.write("        </div>\r\n");
      out.write("        <div class=\"testimonial-item bg-light rounded p-5\">\r\n");
      out.write("          <p class=\"fs-5\">Tempor stet labore dolor clita stet diam amet ipsum dolor duo ipsum rebum stet dolor amet diam stet. Est stet ea lorem amet est kasd kasd erat eos</p>\r\n");
      out.write("          <div class=\"d-flex align-items-center bg-white me-n5\" style=\"border-radius: 50px 0 0 50px;\">\r\n");
      out.write("            <img class=\"img-fluid flex-shrink-0 rounded-circle\" src=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${pageContext.request.contextPath}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/img/testimonial-3.jpg\" style=\"width: 90px; height: 90px;\">\r\n");
      out.write("            <div class=\"ps-3\">\r\n");
      out.write("              <h3 class=\"mb-1\">Client Name</h3>\r\n");
      out.write("              <span>Profession</span>\r\n");
      out.write("            </div>\r\n");
      out.write("            <i class=\"fa fa-quote-right fa-3x text-primary ms-auto d-none d-sm-flex\"></i>\r\n");
      out.write("          </div>\r\n");
      out.write("        </div>\r\n");
      out.write("      </div>\r\n");
      out.write("    </div>\r\n");
      out.write("  </div>\r\n");
      out.write("  <!-- Testimonial End -->\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("  <!-- Footer Start -->\r\n");
      out.write("  ");
      out.write("\r\n");
      out.write("\r\n");
      out.write("<html>\r\n");
      out.write("<head>\r\n");
      out.write("    <meta charset=\"utf-8\">\r\n");
      out.write("    <title>KMS - Kindergarten Management software</title>\r\n");
      out.write("    <meta content=\"width=device-width, initial-scale=1.0\" name=\"viewport\">\r\n");
      out.write("    <meta content=\"\" name=\"keywords\">\r\n");
      out.write("    <meta content=\"\" name=\"description\">\r\n");
      out.write("\r\n");
      out.write("    <!-- Favicon -->\r\n");
      out.write("    <link href=\"img/favicon.ico\" rel=\"icon\">\r\n");
      out.write("\r\n");
      out.write("    <!-- Google Web Fonts -->\r\n");
      out.write("    <link rel=\"preconnect\" href=\"https://fonts.googleapis.com\">\r\n");
      out.write("    <link rel=\"preconnect\" href=\"https://fonts.gstatic.com\" crossorigin>\r\n");
      out.write("    <link href=\"https://fonts.googleapis.com/css2?family=Heebo:wght@400;500;600&family=Inter:wght@600&family=Lobster+Two:wght@700&display=swap\" rel=\"stylesheet\">\r\n");
      out.write("\r\n");
      out.write("    <!-- Icon Font Stylesheet -->\r\n");
      out.write("    <link href=\"https://cdnjs.cloudflare.com/ajax/libs/font-awesome/5.10.0/css/all.min.css\" rel=\"stylesheet\">\r\n");
      out.write("    <link href=\"https://cdn.jsdelivr.net/npm/bootstrap-icons@1.4.1/font/bootstrap-icons.css\" rel=\"stylesheet\">\r\n");
      out.write("\r\n");
      out.write("    <!-- Libraries Stylesheet -->\r\n");
      out.write("    <link href=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${pageContext.request.contextPath}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/lib/animate/animate.min.css\" rel=\"stylesheet\">\r\n");
      out.write("    <link href=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${pageContext.request.contextPath}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/lib/owlcarousel/assets/owl.carousel.min.css\" rel=\"stylesheet\">\r\n");
      out.write("\r\n");
      out.write("    <!-- Customized Bootstrap Stylesheet -->\r\n");
      out.write("    <link href=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${pageContext.request.contextPath}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/css/bootstrap.min.css\" rel=\"stylesheet\">\r\n");
      out.write("\r\n");
      out.write("    <!-- Template Stylesheet -->\r\n");
      out.write("    <link href=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${pageContext.request.contextPath}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/css/style.css\" rel=\"stylesheet\">\r\n");
      out.write("</head>\r\n");
      out.write("<body>\r\n");
      out.write("\r\n");
      out.write("<div class=\"container-fluid bg-dark text-white-50 footer pt-5 mt-5 mxt\">\r\n");
      out.write("    <div class=\"container py-5\">\r\n");
      out.write("        <div class=\"row g-5\">\r\n");
      out.write("            <div class=\"col-lg-3 col-md-6\">\r\n");
      out.write("                <h3 class=\"text-white mb-4\">Get In Touch</h3>\r\n");
      out.write("                <p class=\"mb-2\"><i class=\"fa fa-map-marker-alt me-3\"></i>123 Street, New York, USA</p>\r\n");
      out.write("                <p class=\"mb-2\"><i class=\"fa fa-phone-alt me-3\"></i>+012 345 67890</p>\r\n");
      out.write("                <p class=\"mb-2\"><i class=\"fa fa-envelope me-3\"></i>info@example.com</p>\r\n");
      out.write("                <div class=\"d-flex pt-2\">\r\n");
      out.write("                    <a class=\"btn btn-outline-light btn-social\" href=\"\"><i class=\"fab fa-twitter\"></i></a>\r\n");
      out.write("                    <a class=\"btn btn-outline-light btn-social\" href=\"\"><i class=\"fab fa-facebook-f\"></i></a>\r\n");
      out.write("                    <a class=\"btn btn-outline-light btn-social\" href=\"\"><i class=\"fab fa-youtube\"></i></a>\r\n");
      out.write("                    <a class=\"btn btn-outline-light btn-social\" href=\"\"><i class=\"fab fa-linkedin-in\"></i></a>\r\n");
      out.write("                </div>\r\n");
      out.write("            </div>\r\n");
      out.write("            <div class=\"col-lg-3 col-md-6\">\r\n");
      out.write("                <h3 class=\"text-white mb-4\">Quick Links</h3>\r\n");
      out.write("                <a class=\"btn btn-link text-white-50\" href=\"\">About Us</a>\r\n");
      out.write("                <a class=\"btn btn-link text-white-50\" href=\"\">Contact Us</a>\r\n");
      out.write("                <a class=\"btn btn-link text-white-50\" href=\"\">Our Services</a>\r\n");
      out.write("                <a class=\"btn btn-link text-white-50\" href=\"\">Privacy Policy</a>\r\n");
      out.write("                <a class=\"btn btn-link text-white-50\" href=\"\">Terms & Condition</a>\r\n");
      out.write("            </div>\r\n");
      out.write("            <div class=\"col-lg-3 col-md-6\">\r\n");
      out.write("                <h3 class=\"text-white mb-4\">Photo Gallery</h3>\r\n");
      out.write("                <div class=\"row g-2 pt-2\">\r\n");
      out.write("                    <div class=\"col-4\">\r\n");
      out.write("                        <img class=\"img-fluid rounded bg-light p-1\" src=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${pageContext.request.contextPath}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/img/classes-1.jpg\" alt=\"\">\r\n");
      out.write("                    </div>\r\n");
      out.write("                    <div class=\"col-4\">\r\n");
      out.write("                        <img class=\"img-fluid rounded bg-light p-1\" src=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${pageContext.request.contextPath}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/img/classes-2.jpg\" alt=\"\">\r\n");
      out.write("                    </div>\r\n");
      out.write("                    <div class=\"col-4\">\r\n");
      out.write("                        <img class=\"img-fluid rounded bg-light p-1\" src=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${pageContext.request.contextPath}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/img/classes-3.jpg\" alt=\"\">\r\n");
      out.write("                    </div>\r\n");
      out.write("                    <div class=\"col-4\">\r\n");
      out.write("                        <img class=\"img-fluid rounded bg-light p-1\" src=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${pageContext.request.contextPath}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/img/classes-4.jpg\" alt=\"\">\r\n");
      out.write("                    </div>\r\n");
      out.write("                    <div class=\"col-4\">\r\n");
      out.write("                        <img class=\"img-fluid rounded bg-light p-1\" src=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${pageContext.request.contextPath}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/img/classes-5.jpg\" alt=\"\">\r\n");
      out.write("                    </div>\r\n");
      out.write("                    <div class=\"col-4\">\r\n");
      out.write("                        <img class=\"img-fluid rounded bg-light p-1\" src=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${pageContext.request.contextPath}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/img/classes-6.jpg\" alt=\"\">\r\n");
      out.write("                    </div>\r\n");
      out.write("                </div>\r\n");
      out.write("            </div>\r\n");
      out.write("            <div class=\"col-lg-3 col-md-6\">\r\n");
      out.write("                <h3 class=\"text-white mb-4\">Newsletter</h3>\r\n");
      out.write("                <p>Dolor amet sit justo amet elitr clita ipsum elitr est.</p>\r\n");
      out.write("                <div class=\"position-relative mx-auto\" style=\"max-width: 400px;\">\r\n");
      out.write("\r\n");
      out.write("                </div>\r\n");
      out.write("            </div>\r\n");
      out.write("        </div>\r\n");
      out.write("    </div>\r\n");
      out.write("</div>\r\n");
      out.write("\r\n");
      out.write("</body>\r\n");
      out.write("</html>\r\n");
      out.write("\r\n");
      out.write("  <!-- Footer End -->\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("  <!-- Back to Top -->\r\n");
      out.write("  <a href=\"#\" class=\"btn btn-lg btn-primary btn-lg-square back-to-top\"><i class=\"bi bi-arrow-up\"></i></a>\r\n");
      out.write("</div>\r\n");
      out.write("\r\n");
      out.write("<!-- JavaScript Libraries -->\r\n");
      out.write("<script src=\"https://code.jquery.com/jquery-3.4.1.min.js\"></script>\r\n");
      out.write("<script src=\"https://cdn.jsdelivr.net/npm/bootstrap@5.0.0/dist/js/bootstrap.bundle.min.js\"></script>\r\n");
      out.write("<script src=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${pageContext.request.contextPath}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/lib/wow/wow.min.js\"></script>\r\n");
      out.write("<script src=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${pageContext.request.contextPath}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/lib/easing/easing.min.js\"></script>\r\n");
      out.write("<script src=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${pageContext.request.contextPath}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/lib/waypoints/waypoints.min.js\"></script>\r\n");
      out.write("<script src=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${pageContext.request.contextPath}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/lib/owlcarousel/owl.carousel.min.js\"></script>\r\n");
      out.write("\r\n");
      out.write("<!-- Template Javascript -->\r\n");
      out.write("<script src=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${pageContext.request.contextPath}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/js/main.js\"></script>\r\n");
      out.write("</body>\r\n");
      out.write("</html>\r\n");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }

  private boolean _jspx_meth_c_005fif_005f0(javax.servlet.jsp.PageContext _jspx_page_context)
          throws java.lang.Throwable {
    javax.servlet.jsp.PageContext pageContext = _jspx_page_context;
    javax.servlet.jsp.JspWriter out = _jspx_page_context.getOut();
    //  c:if
    org.apache.taglibs.standard.tag.rt.core.IfTag _jspx_th_c_005fif_005f0 = (org.apache.taglibs.standard.tag.rt.core.IfTag) _005fjspx_005ftagPool_005fc_005fif_0026_005ftest.get(org.apache.taglibs.standard.tag.rt.core.IfTag.class);
    boolean _jspx_th_c_005fif_005f0_reused = false;
    try {
      _jspx_th_c_005fif_005f0.setPageContext(_jspx_page_context);
      _jspx_th_c_005fif_005f0.setParent(null);
      // /Views/common/header.jsp(57,12) name = test type = boolean reqTime = true required = true fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
      _jspx_th_c_005fif_005f0.setTest(((java.lang.Boolean) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${sessionScope.user != null}", boolean.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null)).booleanValue());
      int _jspx_eval_c_005fif_005f0 = _jspx_th_c_005fif_005f0.doStartTag();
      if (_jspx_eval_c_005fif_005f0 != javax.servlet.jsp.tagext.Tag.SKIP_BODY) {
        do {
          out.write("\r\n");
          out.write("                <li class=\"nav-item\">\r\n");
          out.write("                    <a class=\"nav-link\" href=\"viewprofile\">Hello, ");
          out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${sessionScope.user.fullname}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
          out.write("</a>\r\n");
          out.write("                </li>\r\n");
          out.write("                <li class=\"nav-item\">\r\n");
          out.write("                    <a class=\"nav-link\" href=\"logout\">Logout</a>\r\n");
          out.write("                </li>\r\n");
          out.write("            ");
          int evalDoAfterBody = _jspx_th_c_005fif_005f0.doAfterBody();
          if (evalDoAfterBody != javax.servlet.jsp.tagext.BodyTag.EVAL_BODY_AGAIN)
            break;
        } while (true);
      }
      if (_jspx_th_c_005fif_005f0.doEndTag() == javax.servlet.jsp.tagext.Tag.SKIP_PAGE) {
        return true;
      }
      _005fjspx_005ftagPool_005fc_005fif_0026_005ftest.reuse(_jspx_th_c_005fif_005f0);
      _jspx_th_c_005fif_005f0_reused = true;
    } finally {
      org.apache.jasper.runtime.JspRuntimeLibrary.releaseTag(_jspx_th_c_005fif_005f0, _jsp_getInstanceManager(), _jspx_th_c_005fif_005f0_reused);
    }
    return false;
  }

  private boolean _jspx_meth_c_005fif_005f1(javax.servlet.jsp.PageContext _jspx_page_context)
          throws java.lang.Throwable {
    javax.servlet.jsp.PageContext pageContext = _jspx_page_context;
    javax.servlet.jsp.JspWriter out = _jspx_page_context.getOut();
    //  c:if
    org.apache.taglibs.standard.tag.rt.core.IfTag _jspx_th_c_005fif_005f1 = (org.apache.taglibs.standard.tag.rt.core.IfTag) _005fjspx_005ftagPool_005fc_005fif_0026_005ftest.get(org.apache.taglibs.standard.tag.rt.core.IfTag.class);
    boolean _jspx_th_c_005fif_005f1_reused = false;
    try {
      _jspx_th_c_005fif_005f1.setPageContext(_jspx_page_context);
      _jspx_th_c_005fif_005f1.setParent(null);
      // /Views/common/header.jsp(69,12) name = test type = boolean reqTime = true required = true fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
      _jspx_th_c_005fif_005f1.setTest(((java.lang.Boolean) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${sessionScope.user == null}", boolean.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null)).booleanValue());
      int _jspx_eval_c_005fif_005f1 = _jspx_th_c_005fif_005f1.doStartTag();
      if (_jspx_eval_c_005fif_005f1 != javax.servlet.jsp.tagext.Tag.SKIP_BODY) {
        do {
          out.write("\r\n");
          out.write("                <a href=\"");
          out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${pageContext.request.contextPath}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
          out.write("/Login.jsp\" class=\"btn btn-primary rounded-pill px-3 d-none d-lg-block\">Sign in</a>\r\n");
          out.write("                <a href=\"");
          out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${pageContext.request.contextPath}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
          out.write("/register.jsp\" class=\"btn btn-primary rounded-pill px-3 d-none d-lg-block\">Sign up</a>\r\n");
          out.write("            ");
          int evalDoAfterBody = _jspx_th_c_005fif_005f1.doAfterBody();
          if (evalDoAfterBody != javax.servlet.jsp.tagext.BodyTag.EVAL_BODY_AGAIN)
            break;
        } while (true);
      }
      if (_jspx_th_c_005fif_005f1.doEndTag() == javax.servlet.jsp.tagext.Tag.SKIP_PAGE) {
        return true;
      }
      _005fjspx_005ftagPool_005fc_005fif_0026_005ftest.reuse(_jspx_th_c_005fif_005f1);
      _jspx_th_c_005fif_005f1_reused = true;
    } finally {
      org.apache.jasper.runtime.JspRuntimeLibrary.releaseTag(_jspx_th_c_005fif_005f1, _jsp_getInstanceManager(), _jspx_th_c_005fif_005f1_reused);
    }
    return false;
  }
}
